version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: db_cms
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: cmsdb
      MYSQL_USER: cmsuser
      MYSQL_PASSWORD: cmspass
    ports:
      - "3306:3306"


  drupal:
    image: drupal:10-apache
    container_name: drupal_cms
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      DRUPAL_DB_HOST: db
      DRUPAL_DB_NAME: cmsdb
      DRUPAL_DB_USER: cmsuser
      DRUPAL_DB_PASSWORD: cmspass


  typo3:
    image: php:8.2-apache
    container_name: typo3_cms
    ports:
      - "8081:80"
    depends_on:
      - db

    command: bash -c "apt-get update && apt-get install -y unzip git && docker-php-ext-install pdo pdo_mysql mysqli && /usr/sbin/apache2ctl -D FOREGROUND"

volumes:
  db_data: